void inicializarVector(int vectorDeEnteros[], int tam);
void cargarVector(int vectorDeEnteros[], int tam);
void mostrarVector(int vectorDeEnteros[], int tam);
void mostrarNumerosNegativos(int vectorDeEnteros[], int tam);
void mostrarPromedioDePositivos(int vectorDeEnteros[], int tam);
int calcularMaximo (int vectorDeEnteros[], int tam);
void mostrarMaximo(int vectorDeEnteros[], int tam);
void mostrarPosicionMaximo (int vectorDeEnteros[], int tam);
int calcularMinimo(int vectorDeEnteros[], int tam);
void mostrar_Minimo_O_Maximo(int vectorDeEnteros[], int tam);
void mostrarMinimo(int vectorDeEnteros[], int tam);
void mostrarPosicionMinimo(int vectorDeEnteros[], int tam);
int show_option_menu(int vector[], int tam);
void ordenarDeMayorAMenor(int vectorDeEnteros[], int tam);
void ordenarDeMenorAMayor(int vectorDeEnteros[], int tam);
void menu_Ordenar_Vector(int vectorDeEnteros[], int tam);
