//#include "Materia.h"
#include "Fechas.h"

typedef struct{
    int legajo;
    int idMateria;
    int estado;
    eFechas fechaDeInscripcion;
}eInscripcion;

int buscar_Libre_Inscripcion(eInscripcion listaDeInscripciones[],int tamInscripcion);
int cargarInscripcion(eInscripcion listaDeInscripciones[], int tamInscripcion, eMateria listaDeMaterias[], int tamMaterias, eAlumno listaDeAlumnos[], int tamAlumnos);
void initInscripcion(eInscripcion listaDeInscripciones[],int tamInscripciones);
/**
AGREGAR:
--MOSTRAR INCRIPCIONES CON NOMBRE DE ALUMNO Y MATERIAS -> CONSULTAR MATERIAS Y ALUMNO CON EL ID DE LA MATERIA Y ALUMNO
--INGRESAR UNA MATERIA Y QUE ME MUESTRE TODOS LOS ALUMNOS DE ESA MATERIA -> TENGO QUE HACER UN MATCH ENTRE EL IDMATERIA Y EL IDINSCRIPCION Y CUANDO ENCUENTRO UNA COINCIDENCIA,
CONSULTO LOS ALUMNOS CON ESE LEGAJO Y LOS MUESTRO
--CANTIDAD DE INSCRIPCIONES A CADA MATERIA POR LOCALIDAD -> ME PARO EN LOCALIDAD, MATCHEO EN LOCALIDAD Y LOCALIDAD DE ALUMNOS Y DESPUES BUSCO EL ALUMNO EN INSCRIPCIONES, CUANTAS VECES ESTA INSCRIPTO ESE ALUMNO, Y LE SUMO AL CONTADOS
--LOCALIDAD CON MAYOR NUMEROS DE ALUMNOS EN PROGRAMACION I -> LO MISMO QUE EL OTRO PERO, AGREGO UN IF EN EL TERCER FOR, PARA QUE SOLO ME CUENTE LOS QUE ESTAN INSCRIPTOS EN PROG I Y DESPUES HAGO UNA BUSQUEDA DEL MAYOR
--TOTAL DE HORAS QUE ESTUDIA UN ALUMNO SELECCIONADO -> ME TENGO QUE PARAR EN ALUMNO Y VEO CUANTAS VECES SE REPITE UNA INSCRIPCION INCLUYENDO AL ALUMNO, Y VOY SUMANDO PARTE POR PARTE EN UN ACUMULADOR Y ME DEVUELVE ESO.
--INSCRIPCIONES EN UNA FECHA DETERMINADA -> TENGO QUE TENER UNA FUNCION QEU COMPARE DOS FECHAS



*/
